# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
plainwhite:
title: Prithayan Barua
  email: prithayan@gatech.edu
  description: > # this means to ignore newlines until "baseurl:"
    Graduate Student at Gatech, working in Prof. Vivek Sarkar's Habanero group
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "http://yourdomain.com" # the base hostname & protocol for your site
  twitter_username: prithayan 
  github_username:  prithayan

# Build settings
markdown: kramdown
